# Generated by Django 5.2.8 on 2025-11-29 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content_rating',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(null=True),
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('poster', models.ImageField(upload_to='')),
                ('first_air_date', models.DateField()),
                ('last_air_date', models.DateField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('popularity', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_language', models.CharField(null=True)),
                ('content_rating', models.CharField(null=True)),
                ('genre', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
