# Generated by Django 5.2.8 on 2025-12-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_content_rating_movie_original_language_tvshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.TimeField(null=True),
        ),
    ]
