# Generated by Django 5.2.8 on 2025-12-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='duration',
            field=models.CharField(null=True),
        ),
    ]
